on:
  workflow_dispatch:

jobs:
  ollama:
    runs-on: ubuntu-latest
    steps:
      - name: Add Swap
        run: |
          sudo dd if=/dev/zero of=/swapfile bs=1G count=8 status=progress
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          echo "Swap enabled:"
          free -h

      - name: Run model
        uses: ai-action/ollama-action@v2
        id: model
        with:
          model: qwen3-vl:2b
          prompt: Explain the basics of machine learning.

      - name: Print response
        run: echo "$response"
        env:
          response: ${{ steps.model.outputs.response }}
